ss_pgtypes = {
    "ss_sold_date_sk": "integer",
    "ss_sold_time_sk": "integer",
    "ss_item_sk": "integer",
    "ss_customer_sk": "integer",
    "ss_cdemo_sk": "integer",
    "ss_hdemo_sk": "integer",
    "ss_addr_sk": "integer",
    "ss_store_sk": "integer",
    "ss_promo_sk": "integer",
    "ss_ticket_number": "integer",
    "ss_quantity": "integer",
    "ss_wholesale_cost": "real",
    "ss_list_price": "real",
    "ss_sales_price": "real",
    "ss_ext_discount_amt": "real",
    "ss_ext_sales_price": "real",
    "ss_ext_wholesale_cost": "real",
    "ss_ext_list_price": "real",
    "ss_ext_tax": "real",
    "ss_coupon_amt": "real",
    "ss_net_paid": "real",
    "ss_net_paid_inc_tax": "real",
    "ss_net_profit": "real",
}

sr_pgtypes = {
    "sr_returned_date_sk": "integer",
    "sr_return_time_sk": "integer",
    "sr_item_sk": "integer",
    "sr_customer_sk": "integer",
    "sr_cdemo_sk": "integer",
    "sr_hdemo_sk": "integer",
    "sr_addr_sk": "integer",
    "sr_store_sk": "integer",
    "sr_reason_sk": "integer",
    "sr_ticket_number": "integer",
    "sr_return_quantity": "integer",
    "sr_return_amt": "real",
    "sr_return_tax": "real",
    "sr_return_amt_inc_tax": "real",
    "sr_fee": "real",
    "sr_return_ship_cost": "real",
    "sr_refunded_cash": "real",
    "sr_reversed_charge": "real",
    "sr_store_credit": "real",
    "sr_net_loss": "real",
}

ss_sel_min, ss_sel_max = 1, 18000
sr_sel_min, sr_sel_max = 1, 18000
